### ISSUE TITLE
bug(build):🐛 Attempt to concatenate local 'version' (a boolean value) when running :Dotnet build

### ISSUE THREAD

**Issue by declanjmurphy** [GustavEikaas/easy-dotnet.nvim#108]
Hi,

Firstly this plugin will be great for moving from other IDEs. I wish I could contribute but currently I don't have time, but I wanted to say thanks for developing such a plugin.

Here is my bug:

I receive an error running :Dotnet build while editing a cs file, csproj file or sln file

Here is the stack trace

```
Error executing Lua callback: ...asy-dotnet.nvim/lua/easy-dotnet/parsers/csproj-parse.lua:88: attempt to concatenate local 'version' (a boolean value)
stack traceback:
	...asy-dotnet.nvim/lua/easy-dotnet/parsers/csproj-parse.lua:88: in function 'get_project_from_project_file'
	...t/easy-dotnet.nvim/lua/easy-dotnet/parsers/sln-parse.lua:33: in function 'cb'
	...lazy/opt/easy-dotnet.nvim/lua/easy-dotnet/extensions.lua:99: in function 'map'
	...t/easy-dotnet.nvim/lua/easy-dotnet/parsers/sln-parse.lua:29: in function 'get_projects_from_sln'
	...opt/easy-dotnet.nvim/lua/easy-dotnet/default-manager.lua:60: in function 'check_default_project'
	...y/opt/easy-dotnet.nvim/lua/easy-dotnet/actions/build.lua:12: in function 'select_project'
	...y/opt/easy-dotnet.nvim/lua/easy-dotnet/actions/build.lua:58: in function 'build'
	.../pack/lazy/opt/easy-dotnet.nvim/lua/easy-dotnet/init.lua:42: in function 'func'
	.../pack/lazy/opt/easy-dotnet.nvim/lua/easy-dotnet/init.lua:63: in function <.../pack/lazy/opt/easy-dotnet.nvim/lua/easy-dotnet/init.lua:59>
```

The root cause (within `csproj-parse.lua`) seems to be that `extract_from_project` is returning a boolean, which causes `extract_version` to do the same. This results in `get_project_from_project_file` to fail on the following line. 

```lua
local bin_path = vim.fs.joinpath(vim.fs.dirname(project_file_path), "bin", "Debug", "net" .. version)
```

I am using configuration without any options specified using the example from your readme

Thanks for your time!

**Comment by GustavEikaas** [comment]
Huh this is weird, i was certain that version was mandatory in every csproject file. Does your csproject not have a Target framework property?

```
<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
  </PropertyGroup>
</Project>
```

**Comment by declanjmurphy** [comment]
I have the TargetFramework

but I think I found the problem - it's trying to open an unreadable file - because the path from the sln file is not usable as a file system path

I made the below change to sln-parse.lua to add a print

```
-- Generates a relative path from cwd to the project.csproj file
local function generate_relative_path_for_project(path, slnpath)
  local dir = vim.fs.dirname(slnpath)
  local res = vim.fs.joinpath(dir, path)
  print(res)
  return res
end
```

This outputs `./Zagreus\Zagreus.csproj`, which won't work when opening files on mac or linux because of the backslash - I believe this comes from the sln file

```
Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "Zagreus", "Zagreus\Zagreus.csproj", "{A619EEAA-9E34-495F-8C19-4D6B71E13E66}"
```

I hope that helps, let me know if I can provide any other information

**Comment by GustavEikaas** [comment]
Could you change the line to this and see if it fixes the issue? The path is valid if `\` is replaced with `/` right?
```lua
local res = vim.fs.joinpath(dir, path):gsub("\\", "/")
```

**Comment by declanjmurphy** [comment]
Yes, can confirm this worked

Note: I also had to change the terminal option to remove the "\r" being sent to term, or it wouldn't find the project file selected from the picker 

I can see this is configurable by the user which is enough for me, but mention it in case you want to make this os agnostic too 🙂 

Thanks for your support and for running this project!

**Comment by GustavEikaas** [comment]
Awesome ill make a fix for it right away!
Yes my goal is to make this agnostic. Ill have to start testing in WSL aswell. Thanks for raising this issue!

**Comment by GustavEikaas** [comment]
`\r` is also fixed now
