### ISSUE TITLE
feat:🎁 Basic nuget support

### ISSUE THREAD

**Issue by GustavEikaas** [GustavEikaas/easy-dotnet.nvim#124]
## Description
Add some nuget functionality for common things like updating/installing/removing packages. 

## Nuget
- [ ] Add nuget feed (low abstraction value)
- [ ] Remove nuget feed (low abstraction value)

## Packages
- [x] Search for packages (Partly solved by #129, autocomplete inside .csproj)
- [ ] Install package
- [ ] Remove package
- [ ] Update package

**Comment by cbosvik** [comment]
Did you try [dotnet.nvim](https://github.com/MoaidHathot/dotnet.nvim)? It basically adds good nuget and reference support.

**Comment by GustavEikaas** [comment]
Ill check it out, in any case I would want my plugin to implement a good experience for working with nuget packages
