### ISSUE TITLE
feat:🎁 run profile (from launchSettings.json)

### ISSUE THREAD

**Issue by kirill-lappo-dg7** [GustavEikaas/easy-dotnet.nvim#135]
I haven't noticed that feature in current implementation.

One of the useful features would be a run project via profile.

Probably, it could be combined with run project selection, so you could select between project run and profile run.

**Comment by GustavEikaas** [comment]
Made a simple implementation of this, feel free to test it out!
Branch: `feat/launch-profile`

**Comment by kirill-lappo-dg7** [comment]
> Feel free to add details about how you utilize profiles in your dev workflow

I use them on daily basis =) Mostly for switching between test environments I run services against, it is pretty easy to overwrite some config values using environment section of launch config

**Comment by kirill-d-lappo** [comment]
me again, I tried feature branch on two projects, it worked for one of them only, idk why

I pushed project where it didn't work, it is a little demo project, nothing special: https://github.com/kirill-d-lappo/hot-chocolate-demo

https://github.com/user-attachments/assets/86cf7924-dc35-4ab7-a1f5-8426b51a85a3

**Comment by kirill-d-lappo** [comment]
I debugged a little bit, found out that picker does not pop up for some reason at
https://github.com/GustavEikaas/easy-dotnet.nvim/blob/81bbeece89c788910252406a37fe8e951e17ff3a/lua/easy-dotnet/actions/run.lua#L35

**Comment by GustavEikaas** [comment]
Thanks for sharing a repository, I managed to reproduce the error. Im looking into it

**Comment by GustavEikaas** [comment]
I managed to resolve the issue in the latest commit, something weird about yielding and resuming coroutines in lua

**Comment by GustavEikaas** [comment]
Made some changes so if passing true to the function it will persist your selections and the next time you call it will just automatically run without any telescope prompts. Just like run_default works

**Comment by kirill-d-lappo** [comment]
tested today, works fine

I had to bind run_with_profile(true) to a separate keys, so I could always change selected profile

![image](https://github.com/user-attachments/assets/92a242dd-ffed-4514-98f0-acf0d410c88e)

**Comment by GustavEikaas** [comment]
Do you have any suggestions for how to improve the dx? Or is it fine with two keybinds?

**Comment by kirill-d-lappo** [comment]
@GustavEikaas I am totally new to neovim, so my thoughts would be not really beneficial.

I am ok with `run(true)` action by default and having a separate action to run other project if I need

and, to be honest, i am not really into vim shortcuts atm, need to get to know them better

**Comment by GustavEikaas** [comment]
Awesome! I started learning vim in January this year and at this point i will probably never go back to vscode!
Its an awesome tool. If you have any further suggestions in the future dont be shy

Im gonna merge the pr soon, thanks for the good suggestion and followup on the issue!
