### ISSUE TITLE
bug:🐛 build_quickfix: wrong logpath parsing for windows

### ISSUE THREAD

**Issue by yosefham** [GustavEikaas/easy-dotnet.nvim#148]
Hello,
Thanks for the great plugin, it's very helpful to move away from IDEs.

### The bug:
I'm facing an issue when using `build_quickfix` & `build_default_quickfix` in  Windows (works fine in Linux)

![image](https://github.com/user-attachments/assets/60e7c5e8-2001-47a7-8f6e-3392325fbf04)

After some debugging, it seems to be due to wrong `logPath` parsing in windows [here](https://github.com/GustavEikaas/easy-dotnet.nvim/blob/942467f4b2148bd9c924dee8dba2867980f9ea25/lua/easy-dotnet/actions/build.lua#L109) and subsequentially [here](https://github.com/GustavEikaas/easy-dotnet.nvim/blob/942467f4b2148bd9c924dee8dba2867980f9ea25/lua/easy-dotnet/constants.lua#L5)

`Vim.fs.join()` joins strings using `/` while win's paths are using `\`, which ends up producing an inaccessible path. see [vim.fs.join](https://neovim.io/doc/user/lua.html#vim.fs.joinpath())

maybe related somehow to: https://github.com/GustavEikaas/easy-dotnet.nvim/issues/108

### Possible Solution:
Normalize the resulting path to `/` using [vim.fs.normalize](https://neovim.io/doc/user/lua.html#vim.fs.normalize()) with `opt.win = true` (default behaviour), which should work for both linux and windows (I can't say in mac though)

**Comment by GustavEikaas** [comment]
Interesting, im also running windows but im not facing this issue. Granted I have wsl installed and running it in windows terminal. I can make a fix for it, thanks for letting me know!

**Comment by GustavEikaas** [comment]
Kinda weird actually because the vim.fs.joinpath insists that it normalizes the path


`fs.lua`
![image](https://github.com/user-attachments/assets/bbbc64fd-da21-4a69-aba5-e8ab8c0f6f64)

**Comment by yosefham** [comment]
I think getting a path in wsl results in a path using `/` which work fine.

> Interesting, im also running windows but im not facing this issue. Granted I have wsl installed and running it in windows terminal. I can make a fix for it, thanks for letting me know!

**Comment by GustavEikaas** [comment]
Would you mind testing #149 for me. I tested by printing out the paths and there are no `\` characters only `/`.
I also made sure all `vim.fn.stdpath` are wrapped in `vim.fs.normalize`

**Comment by yosefham** [comment]
The path is parsed correctly now, but the `build.log` file is not being created though

**Comment by GustavEikaas** [comment]
On the latest commit i added a print(command). Can you take that command and run it in a normal terminal to see if the file is being created then? Seems weird it didnt work

**Comment by yosefham** [comment]
I think is due to the quote [here](https://github.com/GustavEikaas/easy-dotnet.nvim/blob/942467f4b2148bd9c924dee8dba2867980f9ea25/lua/easy-dotnet/actions/build.lua#L117)

without quotes, it works fine

![image](https://github.com/user-attachments/assets/8704346e-b025-4f0d-8892-ff18f5beff36)

**Comment by yosefham** [comment]
> On the latest commit i added a print(command). Can you take that command and run it in a normal terminal to see if the file is being created then? Seems weird it didnt work

![image](https://github.com/user-attachments/assets/758b622d-2c2c-416f-b24a-1060e239e506)

**Comment by GustavEikaas** [comment]
Very strange behaviour, can you for fun try and run the command but change the `/` to `\` in the path?
Does your `~/AppData/local/nvim-data` directory exist?

**Comment by yosefham** [comment]
yes, my `nvim-data` directory exist.

without quotes `'`, it works with both `/` & `\`
with quotes, it doesn't work in any case

and it doesn't seem to matter if `csprj` path is using the same slash or different than logpath

**Comment by GustavEikaas** [comment]
Great, I updated to remove quotes. Should work for you now

**Comment by yosefham** [comment]
works like a charm now, many thanks for the prompt help.

**Comment by yosefham** [comment]
Hey @GustavEikaas, this parsing is happening in multiple places (test runner, outdated, and probably more, I haven't tested the debugger yet)
I'm new to the hole open source collaboration thing, what do you think it makes more sense;
1. Open a different issue
2. reopen this one

I'm happy to submit a PR if you prefer

**Comment by GustavEikaas** [comment]
As far as I could tell this was only an issue where `vim.fn.stdpath` was invoked which is only in constants.lua. Are you still experiencing issues?

**Comment by yosefham** [comment]
well, there are multiple functions to get path, and all of them seem to have this behaviour, for example:
* `vim.fn.expand` like [here](https://github.com/GustavEikaas/easy-dotnet.nvim/blob/43ab823c52f84860a367edc83237da416e19ee9e/lua/easy-dotnet/outdated/outdated.lua#L51) 
* `vim.fn.getcwd` like [here](https://github.com/GustavEikaas/easy-dotnet.nvim/blob/43ab823c52f84860a367edc83237da416e19ee9e/lua/easy-dotnet/test-runner/runner.lua#L158)
* `os.tnpname` like [here](https://github.com/GustavEikaas/easy-dotnet.nvim/blob/43ab823c52f84860a367edc83237da416e19ee9e/lua/easy-dotnet/test-runner/runner.lua#L159)

##

there are also issues with quotes: [here](https://github.com/GustavEikaas/easy-dotnet.nvim/blob/43ab823c52f84860a367edc83237da416e19ee9e/lua/easy-dotnet/test-runner/keymaps.lua#L107) and similar comands in the same file


however, there is a tricky situation, for test discovery [here](https://github.com/GustavEikaas/easy-dotnet.nvim/blob/43ab823c52f84860a367edc83237da416e19ee9e/lua/easy-dotnet/test-runner/runner.lua#L161), 
![image](https://github.com/user-attachments/assets/c66672bd-321b-401d-a77c-0642be245761)


since `vstest.console.dll` is usually located at `C:/Program Files/dotnet/sdk/8.0.401/vstest.console.dll`, this command would fail without quotes because of the space in `Program Files`, and single quote doesn't work for it either, it has to be double quotes, meaning, for it to work on windows, the path should be `C:/"Program Files"/dotnet/sdk/...`
[get_sdk_path](https://github.com/GustavEikaas/easy-dotnet.nvim/blob/43ab823c52f84860a367edc83237da416e19ee9e/lua/easy-dotnet/options.lua#L11) should be:
```local base = isWindows and 'C:/"Program Files"/dotnet/sdk' or "/usr/lib/dotnet/sdk"```

##
as you see there are a number of places affected

**Comment by GustavEikaas** [comment]
Oh I see now. If you want to make a PR that would be awesome! Way easier for you to test than me. Otherwise I can look at it but will require you to test it before I merge?
What do you think?

**Comment by yosefham** [comment]
yes, I can open a PR for it

**Comment by yosefham** [comment]
pr #160 open for this issue, please double check if linux is still working fine
