### ISSUE TITLE
Test counting in the test window 

### ISSUE THREAD

**Issue by molostovvs** [GustavEikaas/easy-dotnet.nvim#173]
It would be nice to add test counting in solution/folder/project like in rider. 

![image](https://github.com/user-attachments/assets/a7317458-2e70-499f-96e4-d3f3d0642c96)

**Comment by GustavEikaas** [comment]
Great suggestion! Kinda busy at work atm but ill make this as soon as I can

**Comment by molostovvs** [comment]
Thanks! 
I looked at the code a little bit and tried to understand how it can be implemented, and it became interesting: why do expand field of Test type is needed?

**Comment by GustavEikaas** [comment]
`expand` field holds the stacktrace for failed tests. 

The code for the testrunner is not my best work. I have been putting off a big rewrite for a while now. I thing going from a list to a tree structure for holding the tests would make the code a lot easier, more performant and more maintainable

**Comment by GustavEikaas** [comment]
Made a PR now to start looking at it, very busy at work atm so will probably take a while
