### ISSUE TITLE
Considerations for razor file compatibility

### ISSUE THREAD

**Issue by gpproton** [GustavEikaas/easy-dotnet.nvim#188]
Hi, was wondering if there's a consideration on enabling a sort of compatibility with editing razor files since the goal of the project is to enable a generally good development experience. I stumbled upon this https://github.com/tris203/rzls.nvim if there's any usefullness or refrence that can be made to allow the ability to work with razor files.

**Comment by GustavEikaas** [comment]
Hmm interesting. Havent given it a lot of thought tbh. Given that we have seblj/roslyn.nvim and the rzls plugin we are pretty much set for LSP stuff. Are there other things other than LSP stuff that vs/rider/dotnet cli does for a developer?

**Comment by gpproton** [comment]
> Hmm interesting. Havent given it a lot of thought tbh. Given that we have seblj/roslyn.nvim and the tris203/rzls.nvim plugin we are pretty much set for LSP stuff. Are there other things other than LSP stuff that vs/rider/dotnet cli does for a developer?
> 
> Any thoughts or ideas for QOL improvements?

My thougths on this was for easy-dotnet once configured common things required for a reasonable development experience, be it console, blazor or MAUI development, for mAUI might be quite the stretch but for everything related to aspnet core  and console to work 100%

**Comment by GustavEikaas** [comment]
I am surely trying to provide a resonable development experience however I am no dotnet expert myself so I rely on engagement from the community when it comes to which features to implement.

I have not worked extensively with Razor pages but AFAIK apart from lsp support there is not that much more to it? 

This plugin does not cover LSP configurations because we have roslyn and rzls plugins.

Is there any specific features you are missing when it comes to razor support?

**Comment by gpproton** [comment]
> I am surely trying to provide a resonable development experience however I am no dotnet expert myself so I rely on engagement from the community when it comes to which features to implement.
> 
> I have not worked extensively with Razor pages but AFAIK apart from lsp support there is not that much more to it?
> 
> This plugin does not cover LSP configurations because we have roslyn and rzls plugins.
> 
> Is there any specific features you are missing when it comes to razor support?

I would say syntax highlighting and error checking in some basic form will be extremely usefull

**Comment by gpproton** [comment]
My thoughts on QOL improvements is mostly around docs and sample of working configs especially with neovim  districutions like LazyVim, NVChad, AstroNvim, etc.
Because not a lot of people what to spend too much time working on neovim configuration, since that's whats attractive about using LazyVIm + easy-dotnet.nvim for myself.

**Comment by GustavEikaas** [comment]
> My thoughts on QOL improvements is mostly around docs and sample of working configs especially with neovim  districutions like LazyVim, NVChad, AstroNvim, etc.
> Because not a lot of people what to spend too much time working on neovim configuration, since that's whats attractive about using LazyVIm + easy-dotnet.nvim for myself.

Thats good feedback, will definitely consider making simple setup guides for various distros.

For syntax highlighting and error highlighting etc you will need the following plugins:

- [Roslyn](https://github.com/seblj/roslyn.nvim)
- [Rzls](https://github.com/tris203/rzls.nvim)

easy-dotnet doesnt provide syntax highlighting or what is considered LSP features. Only the rest. Let me know if you need help configuring these plugins and ill be happy to assist you

**Comment by gpproton** [comment]
> > My thoughts on QOL improvements is mostly around docs and sample of working configs especially with neovim  districutions like LazyVim, NVChad, AstroNvim, etc.
> > Because not a lot of people what to spend too much time working on neovim configuration, since that's whats attractive about using LazyVIm + easy-dotnet.nvim for myself.
> 
> Thats good feedback, will definitely consider making simple setup guides for various distros.
> 
> For syntax highlighting and error highlighting etc you will need the following plugins:
> 
> - [Roslyn](https://github.com/seblj/roslyn.nvim)
> - [Rzls](https://github.com/tris203/rzls.nvim)
> 
> easy-dotnet doesnt provide syntax highlighting or what is considered LSP features. Only the rest. Let me know if you need help configuring these plugins and ill be happy to assist you

I'm currently using LazyVim with easy-dotnet it's working with the basic configuration but clearly it's insufficient and would like an example that includes Rosslyn and Rzls. It would be quite helpful if there're various sample in the wiki section of the repository.

**Comment by gpproton** [comment]
I made some effort to setup both roslyn and rzls myself so razor works now but i'm not certain if everything is correctly setup and see my current config below to see if any improvement is required.

```lua
return {
  {
    "williamboman/mason.nvim",
    config = function()
    local path = require "mason-core.path"

      require("mason").setup({
        install_root_dir = path.concat({ vim.fn.stdpath("data"), "mason" }),
        log_level = vim.log.levels.INFO,
        registries = {
          "github:mason-org/mason-registry",
          "github:mason-org/mason-registry",
        },
      })
    end,
  },
  {
    "GustavEikaas/easy-dotnet.nvim",
    dependencies = { "nvim-lua/plenary.nvim", "nvim-telescope/telescope.nvim" },
    config = function()
      local dotnet = require("easy-dotnet")

      dotnet.setup()
    end,
  },
  {
    "tris203/rzls.nvim",
    opts = {
      config = {
        on_attach = LazyVim.lsp.on_attach,
        capabilities = {},
        path = "~/.local/share/nvim/mason/packages/rzls",
      },
    },
  },
  {
    "seblj/roslyn.nvim",
    ft = "cs",
    opts = {
      -- your configuration comes here; leave empty for default settings
    },
  },
}

```

**Comment by gpproton** [comment]
But i'm unable to correctly configure rzls

```lua
return {
  {
    "williamboman/mason.nvim",
    config = function()
      local path = require("mason-core.path")

      require("mason").setup({
        install_root_dir = path.concat({ vim.fn.stdpath("data"), "mason" }),
        log_level = vim.log.levels.INFO,
        registries = {
          "github:mason-org/mason-registry",
          "github:mason-org/mason-registry",
        },
      })
    end,
  },
  {
    "GustavEikaas/easy-dotnet.nvim",
    dependencies = { "nvim-lua/plenary.nvim", "nvim-telescope/telescope.nvim" },
    config = function()
      local dotnet = require("easy-dotnet")

      dotnet.setup()
    end,
  },
  {
    "tris203/rzls.nvim",
    opts = {
      config = {
        on_attach = LazyVim.lsp.on_attach,
        capabilities = {},
        path = "~/.local/share/nvim/mason/packages/rzls",
      },
    },
  },
  {
    "seblj/roslyn.nvim",
    ft = "cs",
    opts = {},
    args = {
      "--logLevel=Information",
      "--extensionLogDirectory=" .. vim.fs.dirname(vim.lsp.get_log_path()),
      "--razorSourceGenerator=" .. vim.fs.joinpath(
        vim.fn.stdpath("data") --[[@as string]],
        "mason",
        "packages",
        "roslyn",
        "libexec",
        "Microsoft.CodeAnalysis.Razor.Compiler.dll"
      ),
      "--razorDesignTimePath=" .. vim.fs.joinpath(
        vim.fn.stdpath("data") --[[@as string]],
        "mason",
        "packages",
        "rzls",
        "libexec",
        "Targets",
        "Microsoft.NET.Sdk.Razor.DesignTime.targets"
      ),
    },
    -- CONFIG NOT WORKING
    -- config = {
    --   on_attach = require("lspattach"),
    --   capabilities = require("rzls").capabilities,
    --   handlers = require("rzls.roslyn_handlers"),
    -- },
  },
}


```

**Comment by gpproton** [comment]
It's working correctly now thanks so much

**Comment by GustavEikaas** [comment]
Couple of improvements you could make to your easy-dotnet setup is to define the terminal config option and pass all commands to `snacks.terminal`. The default terminal windows in vim are not great but as a plugin developer i cant impose constraints on which plugins are necessary. I havent done this myself with `snacks.terminal` but i use `toggleterm` and it works great.

```lua
-- easy-dotnet options, replace toggleterm with however you interact with snacks.terminal
terminal = function(path, action, args)
        local commands = {
          run = function()
            return string.format("dotnet run --project %s %s", path, args)
          end,
          test = function()
            return string.format("dotnet test %s %s", path, args)
          end,
          restore = function()
            return string.format("dotnet restore %s %s", path, args)
          end,
          build = function()
            return string.format("dotnet build %s %s", path, args)
          end
        }

        local command = commands[action]() .. "\r"
        require("toggleterm").exec(command, nil, nil, nil, "float")
      end,
```

Also it would be nice with some keybindings probably, for building and running?

```lua
-- example for running project by pressing Control + p
vim.keymap.set("n", "<C-p>", function()
    dotnet.run_with_profile(true)
  end)
```
