### ISSUE TITLE
🐛 Dotnet build throws error "Current buffer is not in diff mode"

### ISSUE THREAD

**Issue by SchnozzleCat** [GustavEikaas/easy-dotnet.nvim#20]
Using ``Dotnet build`` and selecting a project gives me the error "Current buffer is not in diff mode".

``Dotnet restore`` works just fine, so not sure what the exact issue is.

![image](https://github.com/user-attachments/assets/a2e97304-2636-4a89-af30-a643c28a0c45)

**Comment by GustavEikaas** [comment]
Seems like there was a bug in the way the terminal was opened and feedkeys were called.  Try updating the package. If you do not use the default options take a look in the readme for where the dotnet command is being run in a new terminal and update accordingly.
Fixed by #22

**Comment by SchnozzleCat** [comment]
That fixed it, thanks!
