### ISSUE TITLE
Feature: Add "test all" kemap

### ISSUE THREAD

**Issue by franroa** [GustavEikaas/easy-dotnet.nvim#33]
I have following problem with the test runner: the tests discovery is adding te tests to a folder going by the namespaces. This is pretty cool, my problem is, however, that I have many tests which has no namespaces at all (cucumber tests).

I wonder if there is a chance of:
- setting all the test under a Folder to be able to run all at once (with subfolders going by namespaces) 
or
- setting a keymap for running all tests independently of the place I am

**Comment by GustavEikaas** [comment]
Personally I have not worked that much with testing in dotnet, im used to them always having a namespace so this is news to me. I added a keymap for running all tests independent of location `<leader>R`. In the future I will probably add some sort of logic that prevents "flat-tests" and assigns them some sort of sensible group name.

**Comment by GustavEikaas** [comment]
Fixed in #34, feel free to test it out and let me know if something doesnt work. I love the feedback!

**Comment by franroa** [comment]
working perfectly! Thanks!
