### ISSUE TITLE
feat(testrunner):🎁 Group flat tests by default group name

### ISSUE THREAD

**Issue by GustavEikaas** [GustavEikaas/easy-dotnet.nvim#35]
In some cases tests does not belong to any namespace. It would be nice to assign these to some sort of default namespace so you can target their execution as a group, and also for a cleaner UI. 

Inspired by: #33

**Comment by GustavEikaas** [comment]
@franroa Do you have example code of how to make a test that shows up as flat?
![image](https://github.com/user-attachments/assets/810228c0-f148-4810-80b7-7c5172a511fd)
I tried this but it still groups by classname.testname

**Comment by franroa** [comment]
Hi! Thanks for working on this and for the other issues!
Yes, I will try to prepare an example tomorrow

**Comment by franroa** [comment]
Hallo! here you have an example:
https://github.com/franroa/specflow_example (in this file you have the test definition in case you want to put some more tests https://github.com/franroa/specflow_example/blob/main/PrimeService.Tests/Feature/Test.feature)

**Comment by GustavEikaas** [comment]
Im struggling a bit with making a "fake" group for flat tests but the PR i linked will atleast group them under the csproject they belong to. Which should hopefully help a little bit

**Comment by franroa** [comment]
I think that is a good improvement. To me is more than enough.

**Comment by franroa** [comment]
thanks!

**Comment by GustavEikaas** [comment]
Closing this issue for now, I really cant imagine fixing this more than I already have by grouping under csproject
