### ISSUE TITLE
feature(testrunner):🎁 Show only failed tests in the testrunner

### ISSUE THREAD

**Issue by franroa** [GustavEikaas/easy-dotnet.nvim#36]
I don't know how hard this could be, but it would be a cool enhancement. I guess we could filter out the ✔ in the buffer (or the corresponding icon). It is not clean but I think this is better than having to run all the test again and parse the results for checking which are failed. 
If we wanted to filter out the failed tests it could get bit more complicated. 

Maybe creating a new output buffer only for failed tests could be an option

**Comment by GustavEikaas** [comment]
Running `<leader>fe` will now filter out all inconclusive, skipped and passed tests leaving only the failed tests. Please test it out and give feedback.
