### ISSUE TITLE
bug(testrunner):🐛 Buffer with that name already exists

### ISSUE THREAD

**Issue by franroa** [GustavEikaas/easy-dotnet.nvim#37]
I am gettings this error when running Dotnet testrunner twice:
```
Error executing Lua callback: .../easy-dotnet.nvim/lua/easy-dotnet/test-runner/render.lua:16: Vim:E95: Buffer with this name already exists
stack traceback:
	[C]: in function 'nvim_buf_set_name'
	.../easy-dotnet.nvim/lua/easy-dotnet/test-runner/render.lua:16: in function 'setBufferOptions'
	.../easy-dotnet.nvim/lua/easy-dotnet/test-runner/render.lua:84: in function 'render'
	.../easy-dotnet.nvim/lua/easy-dotnet/test-runner/runner.lua:91: in function 'runner'
	...hare/nvim/lazy/easy-dotnet.nvim/lua
```

Context:
I have added the filtetype "easy-dotnet" to the edgy.nvim layout, so I can easily hide/open/change/etc.. the window.
Maybe, and also thinking about the other issue (https://github.com/GustavEikaas/easy-dotnet.nvim/issues/36), an option would be to pass an argument to Dotnet testrunner. Something like:
- Dotnet testrunner toggle all (opens or creates a buffer. If it creates the buffer run the discovery job)
- Dotnet testrunner toggle failed (opens or creates a buffer. If it creates the buffer I guess it shoud discover, run and filter failed tests)

**Comment by GustavEikaas** [comment]
I will fix this in the afternoon, interesting thought to have the toggle failed, toggle all. Ill definitely give it a think. 

Fixing the buffer with this name already exists is an easy fix, just check if buffer already exists and restore it or create a new one.


Good catch!

**Comment by GustavEikaas** [comment]
For now I just fixed the buffer name issue by restoring the existing buffer if it exists. Ill think about the dotnet testrunner toggle and dotnet testrunner toggle failed suggestions. I will definitely implement some sort of variant of it
