### ISSUE TITLE
bug(testrunner): Failed discovery notification not working

### ISSUE THREAD

**Issue by franroa** [GustavEikaas/easy-dotnet.nvim#39]
Hi, I had following issue:
When I run the Dotnet testrunner I got jut black buffer. I needed to debug the plugin to realize that the problem was that I didn't compile the project. 
The testrunner output didn't show anything. It would be nice to have the output of the test discovery command showing the error.

**Comment by GustavEikaas** [comment]
Yeah 100% agree. I will implement an error message if the command fails

**Comment by GustavEikaas** [comment]
Fixed!
