### ISSUE TITLE
bug(testrunner): Prevent rerunning the discovery when the buffer exists

### ISSUE THREAD

**Issue by franroa** [GustavEikaas/easy-dotnet.nvim#40]
I am not sure if this can be considered an error or a feature:
The issue is that when I had run the tests, then I hide the window (to focus on my code) and open it again to run the failing tests, the discovery command will run and I loose my working environment.
 
For example, if I am working only on a group of test, some of them are failing, then I hide the testrunner window and open the window again, I need to run the whole group of tests because the render has cleaned the testrunner output, and I don't have the information about the failing tests anymore.

**Comment by GustavEikaas** [comment]
Hmm, I understand your frustration, I can make changes so that the discovery is not rerun if the buffer already exists, but will probably have to add a keybind or command to manually refresh aswell.

**Comment by GustavEikaas** [comment]
Fixed!
