### ISSUE TITLE
bug: sln parser does not support linux

### ISSUE THREAD

**Issue by franroa** [GustavEikaas/easy-dotnet.nvim#41]
Hi, I don't know if you would like a pr from me or you prefer to add changes. 
There is a line which needs to be changed in this repo to work on Linux:

https://github.com/GustavEikaas/easy-dotnet.nvim/blob/main/lua/easy-dotnet/parsers/sln-parse.lua#L27

The addition would be (if not on windows)
```
  line = line:gsub("\\", "/")
```
Or something similar.

The issue is that the plugin is trying to open the files given after parsing the cproj/sln files, and those are written for windows system

**Comment by GustavEikaas** [comment]
Sure, I would love for you to make a PR on this. Im not sure I understand the issue. For the sln parse there is a gsub with path specifiers so specifically where do you want this line to be added. But if you make a PR I would be happy to review
