### ISSUE TITLE
bug(testrunner):🐛 Groups stuck on running

### ISSUE THREAD

**Issue by franroa** [GustavEikaas/easy-dotnet.nvim#72]
Hi, the new test runner works pretty well. I have found only two issues there. Couldn't reproduce the bug from yesterday, where when I run a group of test which stuck on Running then all test stuck on subsequent calls. Indeed, I only found two issues:

#### Running a Group of flat tests:
The group stuck on Running:

Vim:E474: Unidentified byte: Error: Can not add property GetLogsAdmin to Newtonsoft.Json.Linq.JObject. Property with the same name already exists on object.
stack traceback:
	[C]: in function 'json_decode'
	...-dotnet.nvim/lua/easy-dotnet/test-runner/test-parser.lua:113: in function <...-dotnet.nvim/lua/easy-dotnet/test-runner/test-parser.lua:109>

After running a group of flat tests all tests stuck on Running, then when I run just one test, it works

#### Running a group if there is a test with dataclass:
The group stuck on Running:

...easy-dotnet.nvim/lua/easy-dotnet/test-runner/keymaps.lua:55: Status of Gims.API.Test.Exports.CustomExportTaskActionTest.getExportEntitiesCustomerCentralStatusTaskNoCentral was not present in xml file
stack traceback:
	[C]: in function 'error'
	...easy-dotnet.nvim/lua/easy-dotnet/test-runner/keymaps.lua:55: in function 'cb'
	...-dotnet.nvim/lua/easy-dotnet/test-runner/test-parser.lua:115: in function <...-dotnet.nvim/lua/easy-dotnet/test-runner/test-parser.lua:109>

- The first test (not of type dataclass) worked
- The test in the middle is of type dataclass and stucks
- The third test stucks although is not of type DataClass

Then when:
I run the third test, it works
I run the test in the middle:

...easy-dotnet.nvim/lua/easy-dotnet/test-runner/keymaps.lua:55: Status of Gims.API.Test.Exports.CustomExportTaskActionTest.getExportEntitiesCustomerCentralStatusTaskNoCentral was not present in xml file
stack traceback:
	[C]: in function 'error'
	...easy-dotnet.nvim/lua/easy-dotnet/test-runner/keymaps.lua:55: in function 'cb'
	...-dotnet.nvim/lua/easy-dotnet/test-runner/test-parser.lua:115: in function <...-dotnet.nvim/lua/easy-dotnet/test-runner/test-parser.lua:109> function: builtin#18 ...easy-dotnet.nvim/lua/easy-dotnet/test-runner/keymaps.lua:214: Status of Gims.API.Test.Exports.CustomExportTaskActionTest.getExportEntitiesCustomerCentralStatusTaskNoCentral was not present in xml file
stack traceback:
	[C]: in function 'error'
	...easy-dotnet.nvim/lua/easy-dotnet/test-runner/keymaps.lua:214: in function 'cb'
	...-dotnet.nvim/lua/easy-dotnet/test-runner/test-parser.lua:115: in function <...-dotnet.nvim/lua/easy-dotnet/test-runner/test-parser.lua:109>

Interesting is that some test of DataClass annotation work. I need to check what they have in common

**Comment by GustavEikaas** [comment]
I got this error myself when i ran a suite of flat tests because there were two identical testnames. Using MSTest it only gives the testname and not the entire namespace. The tests were not unique but the names were
```
Vim:E474: Unidentified byte: Error: Can not add property GetLogsAdmin to Newtonsoft.Json.Linq.JObject. Property with the same name already exists on object.
stack traceback:
[C]: in function 'json_decode'
...-dotnet.nvim/lua/easy-dotnet/test-runner/test-parser.lua:113: in function <...-dotnet.nvim/lua/easy-dotnet/test-runner/test-parser.lua:109>
```

## 2
Im assuming the second test causes this error and the third test is never handled because the second one threw an error breaking the code execution. Test number 2 uses ClassData but there is no () arguments?. If you look into the `TestResults/<namespace>.xml` you can look for `Gims.API.Test.Exports.CustomExportTaskActionTest.getExportEntitiesCustomerCentralStatusTaskNoCentral``and probably spot if it doesnt exist or the name mismatches
```
...easy-dotnet.nvim/lua/easy-dotnet/test-runner/keymaps.lua:55: Status of Gims.API.Test.Exports.CustomExportTaskActionTest.getExportEntitiesCustomerCentralStatusTaskNoCentral was not present in xml file
```

**Comment by franroa** [comment]
Well, I have tested again.  It seems that the two errors are actually the same case. 
These are my tests failing
![tests](https://github.com/user-attachments/assets/74df12e3-9362-4b3d-b595-1aa543a94042)

As you see, I test the calendar's deletion in a unit test way, so  i test the same action with the same name of the test case `DeleteCalendarTest`. In both cases it throws an error about not finding the arguments of the case, since it is looking to the wrong namespace (looks under Controllers when I run the Handler and viceversa). What I don't understand is why in the Controller case it works. I assume that this because the Controller case has not the DataClass annotation

**Comment by GustavEikaas** [comment]
Ill try to repro, maybe it scans through the lines and does a check for name instead of namespace somewhere

**Comment by GustavEikaas** [comment]
Just to clarify does it work when you run it in any configuration sln, csproject, namespace or directly? Or does it fail no matter what?

**Comment by franroa** [comment]
Hi I tested again. It breaks no matter what. I think it breaks on the namepasce and blocks the parent folders

**Comment by GustavEikaas** [comment]
I managed to reproduce one variant of this error. It seems i forgot to ensure the namespace was the same for when running a classdata group. According to your screenshots and explanation im not convinced this will fix all your issues so ill keep looking into it. But please test the branch if you get the chance
- #73

**Comment by GustavEikaas** [comment]
Given your screenshot I can see the error. The xml parsers only reads the .Results.UnitTestResult objects. But it seems like the InsertCalendarTest is supposed to be a testgroup (aka classdata) but is registered as a singular unit test. 

What annotations are you using for this test? (Theory, inline data etc)

**Comment by franroa** [comment]
I am Using the same annotations for Delete as for Insert: Theory and ClassData. I don't know why they appear different when running dotnet test -t

**Comment by GustavEikaas** [comment]
if dotnet test -t lists it out without parameters then I cant really do much to fix it.

Hopefully the findings from this will give me much more accurate results and fix this issue. Ill keep digging
- #74

**Comment by GustavEikaas** [comment]
Closing this and waiting for someone to report it again, hopefully with a repro
