### ISSUE TITLE
feat(ef):🎁 Entity framework support

### ISSUE THREAD

**Issue by franroa** [GustavEikaas/easy-dotnet.nvim#85]
Hi, I wonder how would you feel if we add commands for entity framework:

## Database (necessary)
- [x] `dotnet ef database drop`
- [x] `dotnet ef database update`

## DbContext (Not sure if necessary)
- [ ] `dotnet ef dbcontext info`
- [ ] `dotnet ef dbcontext list`
- [ ] `dotnet ef dbcontext optimize`
- [ ] `dotnet ef dbcontext scaffold` (typically one-shot)
- [ ] `dotnet ef dbcontext script` 

## Migrations (necessary)
- [x] `dotnet ef migrations add`
- [x] `dotnet ef migrations remove`
- [x] `dotnet ef migrations list`
- [ ] `dotnet ef migrations bundle`
- [ ] `dotnet ef migrations script` //would it be with -o or as stdout?
- [ ] `dotnet ef migrations has-pending-model-changes` //returns ex_code 1 if pending changes

Having a reliable way of creating a recreating migration is cool when developing database schemas

**Comment by GustavEikaas** [comment]
Awesome idea, I have also been thinking about this for some time. I feel like it might need some discussion first. 

Initial thoughts

- dotnet ef doesnt ship with sdk its a separate tool (requires readme on how to install)
- What would the UI look like (when using dotnet ef previously i used it from the terminal)
- Common usecases
- Startup project vs project resolution

**Comment by GustavEikaas** [comment]
Anyone who wants this pls add a +1 in the comments

**Comment by GustavEikaas** [comment]
Resource: https://learn.microsoft.com/en-us/ef/core/cli/dotnet

- [ ] Check installation
- [ ] no-build
- [ ] --startup-project
- [ ] --project
- [ ] --configuration?

Should support following commands


- [ ] `dotnet ef database drop`
- [ ] `dotnet ef database update`

- [ ] `dotnet ef dbcontext info`
- [ ] `dotnet ef dbcontext list`

**Comment by GustavEikaas** [comment]
Resource: https://learn.microsoft.com/en-us/ef/core/cli/dotnet

- [ ] Check installation
- [ ] no-build
- [ ] --startup-project
- [ ] --project
- [ ] --configuration?

Should support following commands


- [ ] `dotnet ef database drop`
- [ ] `dotnet ef database update`

- [ ] `dotnet ef dbcontext info`
- [ ] `dotnet ef dbcontext list`

**Comment by GustavEikaas** [comment]
I am closing this for now as the PR seems to cover the most basic of functionality. Ill rather make new issues for remaining functionality if requested
