### ISSUE TITLE
Add ability to specify configuration for `build`.

### ISSUE THREAD

**Issue by AjayKMehta** [GustavEikaas/easy-dotnet.nvim#86]
This is a great plugin that I look forward to trying out. Thanks for creating this!

It would be very useful for the `build` command to allow specifying the configuration (`Debug`, `Release`). 

In general, it would be nice if all the commands wrapping `dotnet` CLI had an `additional_args` (anybody have a better name?) parameter to specify additional arguments for the commands, e.g. `--no-restore` for build.

**Comment by GustavEikaas** [comment]
This has been mentioned a few times already so I figured ill make a general issue for it #87. Its a great suggestion and something I want to make possible. Please feel free to share your thoughts on the issue below
- #87

**Comment by GustavEikaas** [comment]
Just to clarify for the `terminal` section of your config this is already possible. But yes I would like to expose it in a better more global way

    local dotnet = require("easy-dotnet")
    dotnet.setup({
      test_runner = {
        vstest_path = "C:/Program Files/dotnet/sdk/8.0.108/vstest.console.dll"
      },
      terminal = function(path, action)
        local commands = {
          run = function()
            return "dotnet run --project " .. path .. " --no-restore"
          end,
          test = function()
            return "dotnet test " .. path
          end,
          restore = function()
            return "dotnet restore " .. path
          end,
          build = function()
            return "dotnet build " .. path
          end
        }
        local command = commands[action]() .. "\r"
        require("toggleterm").exec(command, nil, nil, nil, "float")

**Comment by AjayKMehta** [comment]
I am closing this issue since #87 covers this.

**Comment by GustavEikaas** [comment]
This is now supported using `Dotnet build release` #122
