### ISSUE TITLE
feat:🎁 slnx support

### ISSUE THREAD

**Issue by GustavEikaas** [GustavEikaas/easy-dotnet.nvim#88]
Investigate and add support for slnx.
[Research](https://schwabencode.com/blog/2024/04/10/welcome-new-visual-studio-slnx-solution-file#:~:text=The%20new%20format%20is)

Looks pretty straightforward tbh

**Comment by AjayKMehta** [comment]
It doesn't work with dotnet CLI tooling.

Blocked by [this issue ](https://github.com/dotnet/msbuild/issues/10266).

**Comment by GustavEikaas** [comment]
Seemingly available in latest msbuild version

**Comment by GustavEikaas** [comment]
Seems to work really well. Still some missing features in the dotnet sdk though. Looks to be worked on so should arrive shortly
